### PR TITLE
Add List Users function to firebase auth helper

### PR DESCRIPTION
**Pull request by Kaeldehta**

### CODE REVIEW

**Comment by Kaeldehta** [comment]
Hey. I want to stop using the firebase admin sdk entirely so I would like to put the remaining functions like bulk getting users into this package as well.

**Comment by awinogrodzki** [comment]
Hey @Kaeldehta!

Thanks for a PR. Looks good. I will introduce this in upcoming `0.9.0` after some testing :-)

**Comment by awinogrodzki** [comment]
You can ignore test results. The test requires access to secret firebase credentials and fails if PR is made from forked repository. I will take care of it.

**Comment by Kaeldehta** [comment]
Looks good to me.
It might make sense to include the rest of the querying functionality as well in the future.

**Comment by awinogrodzki** [comment]
@Kaeldehta list changes were released in `0.9.4`. Thanks!

**Pull request merged**
