### PR TITLE
Add support for specifying tenant id in middleware.

### PR DESCRIPTION
**Pull request by taeold**
Support specifying `tenantId` in the `authentication` middleware:

```diff
export async function middleware(request: NextRequest) {
  return authentication(request, {
    loginPath: "/api/login",
    logoutPath: "/api/logout",
    apiKey: "YOUR-FIREBASE-API-KEY",
    cookieName: "AuthToken",
+   tenantId: "my-tenant",
    ...
}
```

When `tenantId` is specified, all outgoing request to the Google Identity Platform API will include `tenantId` in the request body when appropriate. Also, the custom token JWT will include `tenantId` claim set to the provided tenant id.

**Note**: The integration test includes test cases for multi-tenant support. This means that the GCP project used for integration test must enable multi-tenant support and have at least one tenant for testing. See [public doc](https://cloud.google.com/identity-platform/docs/multi-tenancy-quickstart).

Once you set up a tenant, make sure you set the environment variable `FIREBASE_AUTH_TENANT_ID` with the tenant id (e.g. `test-tenant-qszw`) before running the integration test.

Fixes https://github.com/awinogrodzki/next-firebase-auth-edge/issues/102

### CODE REVIEW

**Comment by awinogrodzki** [comment]
Hey @taeold!

What keeps you from storing `tenantId` within the token?

Custom claims within the token is a great place to store `tenantId`.

Upon user registration you can `setCustomUserClaims` with `tenantId`. Then, in `handleValidToken` callback, you can access `tenantId` as such:

```tsx
handleValidToken({token, decodedToken}) {
  const tenantId = decodedToken.tenantId;
}
```

Multi-tenancy is just another way of authorizing users for specific content. Custom claims is perfect solution for your issue, because claims can be saved only once, and are accessible within the token itself, which means that the token is always the source of truth when it comes to `tenantId`.

**Comment by taeold** [comment]
@awinogrodzki Thanks for taking your time to respond.

I agree that custom claims would work just as well as using the multi-tenancy feature from GCIP!

There are couple of advantages from using the built-in multi-tenancy that I was hoping to leverage:

* Isolation of identifiers between tenant. This means to me that an account email (e.g. abc@test.com) can be part of multiple tenant without me having to think worry about making `tenantId` be an array instead.

* Customizing identity providers per tenant. E.g. I want offer SAML as a special add-on for each tenant. Multi-tenancy simplifies some of the logic for implementing this kind of offering.
 
* Quota/metric breakdown so it's easy for me track usage (e.g. account sign-up) per tenant.

Like you said, I don't think use of multi-tenancy is necessary for some of the features I want in my custom auth system, but leveraging GCIP's support for multi-tenancy directly will remove some extra work I'd have to build in my application!

Curious to hear what you think!

**Comment by awinogrodzki** [comment]
@taeold, I got your argument. It seems that we can leverage GCP tenantId with little fuss with your implementation.

The implementation looks good. Could you add an integration test based on [verify-token.integration.test](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/224cf71f846e15324d32c7b4e22d8f1232923105/src/auth/test/verify-token.integration.test.ts)?

**Comment by awinogrodzki** [comment]
Released in `next-firebase-auth-edge@0.8.8`

**Comment by taeold** [comment]
@awinogrodzki Thank you for your speedy response! Cheers!

**Pull request merged**
